### PR TITLE
Fix for work with RamStore

### PR DESCRIPTION
**Pull request by AlexKovynev**

### CODE REVIEW

**Comment by kefirfromperm** [comment]
It's wrong!

Hibernate listener is needed not for Quartz but for code in a Job even if RamStore is used.

**Comment by zyro23** [comment]
i think this is duplicated by #50

**Comment by AlexKovynev** [comment]
kefirfromperm: It is right. It do exactly that you say.

**Comment by kefirfromperm** [comment]
No!
SessionBinderJobListener must not depend on jdbcStore

**Comment by kefirfromperm** [comment]
Sorry. You are right.

**Pull request merged**
