### PR TITLE
Correcting initialization of Jobs when autoStart == false. Fix for #59

### PR DESCRIPTION
**Pull request by hbogaards**
I think this is a safe and correct fix for issue #59 

I have not made a test proving the issue and that this fixes it...

### CODE REVIEW

**Comment by zyro23** [comment]
i am not sure if this really fixes it because `scheduleJob(...)` still only happens if `autoStartup`=`true`.
but within `scheduleJob(...)` the `jobDetails` are configured and the triggers are associated with the job.

i would expect `autoStartup`=`false` to not prevent any job configuration or scheduling but to only prevent the scheduler itself from starting which is what it does by passing the `autoStartup` property to the `SchedulerFactoryBean`.

**Comment by hbogaards** [comment]
This fixes it for us.

Our application can now start and then schedule its Jobs and start the Scheduler manually

**Comment by hbogaards** [comment]
@zyro23 Looking (and testing) further with this, I think you are right.
I moved a Job to a different package and then the Job was not correctly configured.

I think that the check on `autoStartup` should be completely removed

**Comment by zyro23** [comment]
just fyi, to get the ("old") behavior i described back, i currently use this ugly workaround:
```groovy
@Component
class SchedulerFactoryBeanPostProcessor implements BeanPostProcessor {

	@Override
	Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
		return bean
	}

	@Override
	Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
		if (bean in SchedulerFactoryBean) {
			((SchedulerFactoryBean) bean).autoStartup = false
		}
		return bean
	}

}
```
which effectively keeps `quartz.autoStartup = true` from a plugin perspective so that the jobs get configured but then disables it directly on the `Scheduler` to prevent it from starting :/

**Pull request merged**
