### PR TITLE
Only add job if it does not exists

### PR DESCRIPTION
**Pull request by tkvw**
If using the jdbcstore and you use persistent jobdatamap, it will be
null the next system restart, because jobdetail is added with replace =
true. Now the system checks if the job already exists.
Furthermore a loadAfter is added for databaseMigration, when you want to
add the databaseschema of quartz using dbm and quartz is loaded before
dbm, it will fail. Loadafter makes sure this does not happen.

### CODE REVIEW

**Comment by bryangcampbell** [comment]
Nice! This is a helpful fix. Ran into this issue several times on developers machines when we first added in quartz. Thanks!

**Comment by svetozar02** [comment]
Any plans to include this in a new version?

**Comment by rvanderwerf** [comment]
So I have had requests to go to other way around - re-add the jobs and remove the old ones. That seems safer no?

**Comment by svetozar02** [comment]
Isn't that going to cause issues if quartz misfires are used? See http://www.nurkiewicz.com/2012/04/quartz-scheduler-misfire-instructions.html

Let's say you have a job that executes at 2am. Your application goes down at 1:55 am and is restarted(and deployed) at 2:05 am. 
If the job is not deleted, quartz will execute the job when it starts due to the misfire policy. 
However, if the job is deleted, the misfire "event" is deleted as well. As result, when quartz starts it won't execute the job because the misfire is not detected. As result, the task scheduled at 2am will not be executed till next day. 

Does this make sense?

**Comment by rvanderwerf** [comment]
understood. I think I may have make it configurable for the user's desired behavior - this feature or the reverse. Also I had a request to check the jobs and see if the application still even has the class it's looking for to run.

**Pull request closed without merging**
