### PR TITLE
Plugin update for grails version 6.1.1 and jdk 11

### PR DESCRIPTION
**Pull request by fernando88to**
**Tasks that were done**

- This pull request presents a comprehensive refactoring of our plugin's unit tests, with the aim of ensuring full compatibility with the latest version of Grails.

- Plugin update for grails version 6.1.1 and jdk 11

- Create command for create-job

- update documentation

**Steps that remain to be taken**

- Generate documentation
- Configure application publication

### CODE REVIEW

**Comment by puneetbehl** [comment]
@Richardson-e  Could you please review this pull-request?

**Review by Richardson-e — APPROVED** [review]

**Comment by dauer** [comment]
I ran into an issue with the 2.0.13 version of the Quartz plugin when upgrading from Grails 4.1.1 -> 6.1.1, so I tried building a local version from @fernando88to branch and that fixed my failing tests - so it looks very promising!

Only thing is that when doing a `gradle publishToMavenLocal` the jar file had `-plain` added to the filename:
`quartz-2.0.14.BUILD-SNAPSHOT-plain.jar`
Expecting:
`quartz-2.0.14.BUILD-SNAPSHOT.jar`

**Comment by puneetbehl** [comment]
@matrei Can you please look into this?

**Comment by matrei** [comment]
> @matrei Can you please look into this?

@puneetbehl There is some overlap with #125.
@fernando88to Good with a rewrite of the tests to spock 👍 .
Can you create a new PR based on 3.0.x with only those?

**Comment by fernando88to** [comment]
> > @matrei Can you please look into this?
> 
> @puneetbehl There is some overlap with #125. @fernando88to Good with a rewrite of the tests to spock 👍 . Can you create a new PR based on 3.0.x with only those?

I am going to do

**Pull request closed without merging**
